---
output:
  pdf_document: default
bibliography:
- book.bib
- packages.bib
editor_options: 
  markdown: 
    wrap: 72
---

`r if(eval_book) '\\allsectionsfont{\\centering}'`
# Abstract {-}

In politics, it is important for political actors to understand populations are inclined to specific political parties. This is a topic of interest to political movements, the media and political science. According to the latter, factors like age, wealth and education can be used as predictors of vote. However, these axioms have been challenged as changes in the political system (like the rise of populism and new political movements) seem to defy conventional knowledge of the political leanings of the electorates.

This project presents an analysis of how voting patterns in Australia are impacted by demographic factors. In particular, it examines how changes in demographic attributes [^fromcensus] influence primary voting [^primaryvotingab] for federal elections for the Commonwealth's House of Representatives.

 [^fromcensus]: From Census data,
 [^primaryvotingab]: First choices in a preferential voting system.

To achieve this objective, Census results were reviewed, and key demographic statistics were selected based on  a review of the existing literature ([@biddle2022], [@votingpatternsbygen], [@jakubowicz]) and media narrative ([@inner-ci2019], [@wehave], [@abcbandaid], [@doesthe]). Code in the form of R packages was written to extract census data and election results systematically and repeatedly. Once data was selected, commonalities across electoral divisions were identified, which were used to classify them into three distinct segments: 1. mostly inner-city areas in large metropolitan areas, 2. the suburban areas in middle, and 3. outer suburbs, and regional and rural constituencies. Then, multivariate elastic net regression models (for each cluster) were fitted to identify which demographic factors influence primary voting for the three largest political groups with national presence (namely the Australian Labor Party, the Coalition and the Australian Greens).

From this composite model, it was possible to establish a link between age, income, religious beliefs, cultural diversity, and primary voting paterrns across all electorates. In particular, it was possible to establish voting in inner-city electorates may be driven by age (younger people voting left, older voting right), income (higher income population favouring both the Greens and the Coalition) and religiosity (non-religious people leaning Green, different religious groups preferring either Labor or the Coalition). Those factors were also found to be relevant in the suburban fringes, where also different culturally diverse communities seem to prefer either Labor or the Coalition. However, in regional areas the same factors seem less relevant, and education levels and higher-income are positively associated with Labor vote.

After fitting this model, a naive retrospective forecast of the 2022 election was attempted. Although the model only has a discrete predicting power (as expected), it proves to be a useful analysis tool to understand the drivers behind changes in voting patterns. Some particular examples are presented, including the results of the so-called "Teal Wave". In those cases it is possible to observe that the Coalition vote was in-line with demographic expectations, concluding that teal MPs weren't elected backed by dissatisfied Coalition voters. Another case presented examines the continuous growth of the Green vote in selected inner-city electorates, driven by generational change and gentrification. Finally, a more diverse set of electorates were also analysed, looking for cases where the selected variables did not necessarily correctly interpret the results. This was deemed useful to understand potential limitations.

To conclude, a series of improvements were suggested to improve predictive and analytical power.

\newpage
