---
output:
  pdf_document: default
bibliography:
- book.bib
- packages.bib
---
# Method {#method}

Going back to the introduction, the objective of the exercise is to determine if demographic attributes can influence or explain voting patterns. This can be restated into determining if demographic attributes can serve as predictors of primary voting. In mathematical terms, this can be expressed in a simple way by equation \@ref(eq:equation1).

```{=tex}
\begin{align}
\mathbf{Y} = f(\mathbf{X})
(\#eq:equation1)
\end{align}
```
where $\mathbf{Y}$ represents a vector with primary voting for an electorate, and $\mathbf{X}$ represents the vector of respective demographic attributes. 

In this simple form, other factors that may influence voting are not explicitly shown in the equation. However, these factors may be difficult to quantify as they potentially relate to a myriad of factors including the state of the economy, foreign affairs, perceptions about the governing party or any party in the election, or the mood of the times.

To solve this challenge, it is possible to naively assume tools like polling can effectively capture the *zeitgeist*. If that is the case, it is possible to split the original function $f()$ into a poll component and a demographic component. Since it is not in the scope of this project, we can also ignore the polling component and focus on the difference between the absolute value and polling results. To further simplify things, we can temporarily assume that polling results are uniform across the country, thus demographic statistics only influence the difference between the electorates' primary vote and the respective national percentage. This is expressed by equation  \@ref(eq:equation2), which also accounts for general error.

```{=tex}
\begin{align}
\mathbf{Y} = f(\mathbf{X}) + \epsilon
(\#eq:equation2)
\end{align}

where  \\
$\mathbf{Y}  = \mathbf{Y} - \mathbf{Yp}$ \\
$\mathbf{X}  = \mathbf{X} - \mathbf{Xn}$ \\ 
and  \\
$\mathbf{Yp} : \textrm{Primary voting polling results}$ \\
$\mathbf{Xn} : \textrm{Demographic values at national level}$ \\ 

```
This second iteration does not take into account that in different electorates, different demographic attributes may have a different effect on the primary vote. For instance, in more progressive areas, a higher proportion of younger people may have a greater effect on left-leaning preferences when compared with similar proportions of younger people in rural electorates.  Equation  \@ref(eq:equation3) is intended to acknowledge those differences.
  
```{=tex}
\begin{align}
\mathbf{Y_i} = f_i(\mathbf{X_i}) + \epsilon 
(\#eq:equation3)
\end{align}

where  \\
$\mathbf{Y}  = \mathbf{Y} - \mathbf{Yp_i}$ \\
$\mathbf{X}  = \mathbf{X} - \mathbf{Xn_i}$ \\ \\
```
      
It is worth noticing that $i$ represents a particular grouping of electorates,  and for each group predictors can be different - as different attributes may have different impacts.
    
In terms of choosing an appropriate $f_i$, it would depend on the objective of the model. Given the large number of predictors and requirements on interpretability and accuracy, this could be a complex task. In this particular case, the focus is on understanding the factors that influence voting rather than producing accurate electoral predictions. After examining possible alternatives a model in the **regularised regression** family is deemed as an appropriate choice. The selection is based on the following factors:

* Regularised models are a good fit in cases with a large number of variables. Lasso regression in particular is a good method for variable selection, helping to identify the most relevant parameters.
* Regularised regression models can also deal with predictors exhibiting a high level of collinearity.
* The results provide an straightforward interpretation on how each predictor influences the results. In the context of this projects, that is a more important priority than forecasting accuracy.

Consequently,  the task at hand consists in finding the regularised regression coefficients for the set of formulas represented by equation \@ref(eq:equation4)
    
```{=tex}
\begin{align}
\left(\begin{array}{c} 
y_{i1}\\ 
y_{i2}\\ 
... \\
y_{in}\\ 
\end{array}\right) =
\left(\begin{array}{cccc} 
\beta_{i11} & \beta_{i12} & ... &  \beta_{i1m}\\
\beta_{i21} & \beta_{i22} & ... &  \beta_{i2m}\\
 ...         & ...         & ... & ...         \\
\beta_{in1} & \beta_{in2} & ... &  \beta_{inm}\\
\end{array}\right)
\left(\begin{array}{c} 
x_{i1} \\
x_{i2} \\
...    \\
x_{im}
\end{array}\right) +
\left(\begin{array}{c} 
\epsilon_{i1}\\ 
\epsilon_{i2}\\ 
... \\
\epsilon_{in}\\ 
\end{array}\right)
(\#eq:equation4)
\end{align}
```
   
        
A complication of this approach is that requires separating the electorates into different segments. This requires having a method to map electorates into clusters if such an assignment is not provided. Thus, the modelling task consists of:
        
- A classification model map new records into clusters with similar electorates.
- A regularised regression model to determine how demographic factors influence primary voting for each party.      

```{r}
rm(list=ls()[!(ls() %in% keep_vars)])
```
