--- 
title           : "Analysing Australian Election Results"
author          : "Carlos Yanez Santibanez"
programme       : "Data Analytics MSc (ODL)"
subject         : "Project"
date            : !r Sys.Date()
output: pdf_document
params:
  book: FALSE
  html: TRUE
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(readr)
library(stringr)
library(here)
library(auspol)
library(ggplot2)
library(tidyr)
library(fs)
library(tidymodels)
library(vip)
library(glue)
library(kableExtra)
library(flowdiagramr)
#flextable::add_latex_dep(TRUE,TRUE)
source(here::here("formatting_defaults.R"))

project_path <- fs::path(here(),"..")

knitr::opts_knit$set(message=FALSE,echo=FALSE,warning=FALSE,cache=TRUE)
knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)

eval_book <- params$book
eval_html <- params$html

if(eval_html){
  library(leaflet)
  library(htmltools)
  library(plotly)
  library(crosstalk)
}

keep_vars <- c(ls(),"keep_vars")


```

```{r eval=eval_book}
uofgdataanalyticsreport::cd_page_title()
```
 

```{r eval=FALSE, include=FALSE}
bookdown::render_book("index.Rmd", "bookdown::gitbook",params=list(book=FALSE,html=TRUE))
bookdown::render_book("index.Rmd", "bookdown::pdf_book",params=list(book=TRUE,html=FALSE))

```

`r if(eval_book)'\\cleardoublepage \\pagenumbering{roman}'`
