---
output:
  pdf_document: default
  html_document: default
---
# Sourcing Data {#data}

Based on the previously explained approach, data had to be source from 2 main sources:

- The Australian Electoral Commission (AEC). The AEC contains detailed online records for all federal election held in the 21st century, through their Tally Room websites. All data is presented in CSV format and it is publicly and easily accessible.

- The Australian Bureau of Statistics (ABS). The ABS provides an extensive repository of statistical data. This project is using Census Data, which is available through their Census Data packs.

In both cases, the data provided is of high quality, trustable and provided in open formats. However, three particular challenges arose:

- There is a large volume of data: multiple political parties, +100 electoral divisions and a very large number of statistical data collected in each census.
- Not all publicly available Census data is provided by electoral division. Aggregation from statistical collection areas into electorates is not straightforward due to a lack of 1:1 correspondence between the former (defined by the AEC) and the latter (defined by the ABS).
- Despite the best efforts of both organisations, names of electorates, parties, census attributes change over time, requiring work to track a variable across time.

To better overcome those challenges in a repeatable way, three R packages have been created as part of this projects, namely:

- {auspol}, which extracts and presents electoral results.
- {auscensus}, which allows to interact with Census Data Packs to extract different statistics across geographical units, and across censuses.
- {aussiemaps}, which assists with aggregating census data into electoral divisions, by matching and apportioning different geographical structures.

Each package is further detailed in the appendix.

Using the above tools, the extraction pipeline can be represented by figure \@ref(fig:data-flow).

```{r data-flow, fig.cap="Flow of data from sources to dataset", echo=FALSE}
library(DiagrammeR)
library(here)
DiagrammeR::grViz(here("img","02_data_flow.gv"))
```

The main points of the process are explained below.


## Extracting data

`r if (knitr::is_html_output()) '
# References {-}
'`

