---
bibliography: references.bib
---

# (APPENDIX) Extracting Data

A particular challenge for this project was to efficiently and systematically being able to extract data. In this particular case, data sources are public and freely made available by Australian government departments. However, there were two challenging aspects, namely:

-   The volume of data, especially when it comes to Census Data. This also presented a challenge in terms of selection and aggregation of data not presented at electorate level.
-   Changes in file structure and naming convention across time, having to standardise variable names across different census and election years.

The search for existing data packages did not produce satisfactory results - only a package to retrieve historical weather data was found ([{cropgrowdays}](https://gitlab.com/petebaker/cropgrowdays/)[@cropgrowdays]). Therefore, as par of this project it was necessary to create the following R packages:

-   {auspol}, a data package with containing voting tallies for the Australian House of Representatives. This package contains processed data, sourced from the Australian Electoral Commission, as well as functions to access and plot them. In addition to primary votes (the scope for this project), this also contains preferential distribution tallies.

-   {auscensus}, a package to interact with Census Data Packs (as published by the Australian Bureau of Statistics, ABS). This package does not contain the actual data - each data pack ranges from 600 to 800 MB.

-   {aussiemaps}, which is a rewriting of a geospatial package experiment by the author. This package contains geographical boundaries for ABS statistical structures as well as non-ABS geographies such as electoral divisions. In this project, this package is use to aggregate data from granular statistical structures to electorates.

## Package Architecture

The three packages have been designed using the same approach, which can be summarised by the following:

-  Data is not included in the packages, but hosted on GitHub repositories. Given the large size of the data files, they cannot be directly included along code and they are shared "releases"instead. Then, the package functions download data as needed. This applies for metadata for the three packages and the actual data for {auspol} and {aussiemaps}.
